In [1]:
import numpy as np
import pandas as pd
import sys
sys.path.append("../fraud_detection/src/")

from util import s_to_time_format, string_to_datetime,hour_to_range
from tqdm import tqdm

#-----------------------------
# load data
#-----------------------------
df_train = pd.read_csv("/data/yunrui_li/fraud/dataset/train.csv")
df_test = pd.read_csv("/data/yunrui_li/fraud/dataset/test.csv")


for df in [df_train, df_test]:
    # pre-processing
    df["loctm_"] = df.loctm.astype(int).astype(str)
    df.loctm_ = df.loctm_.apply(s_to_time_format).apply(string_to_datetime)
    # time-related feature
    df["loctm_hour_of_day"] = df.loctm_.apply(lambda x: x.hour)
    df["loctm_minute_of_hour"] = df.loctm_.apply(lambda x: x.minute)
    df["loctm_second_of_min"] = df.loctm_.apply(lambda x: x.second)

    # removed the columns no need
    df.drop(columns = ["loctm_", "loctm"], axis = 1, inplace = True)

In [2]:
gby = "bacno"
# df = pd.concat([df_train, df_test], axis = 0)
df_train.sort_values(by = [gby,"locdt","loctm_hour_of_day","loctm_minute_of_hour","loctm_second_of_min"], 
                     inplace = True)
df_test.sort_values(by = [gby,"locdt","loctm_hour_of_day","loctm_minute_of_hour","loctm_second_of_min"], 
                     inplace = True)

In [3]:
pd.options.display.max_columns = 100

df_train

,acqic,bacno,cano,conam,contp,csmcu,ecfg,etymd,flbmk,flg_3dsmk,fraud_ind,hcefg,insfg,iterm,locdt,mcc,mchno,ovrlt,scity,stocn,stscd,txkey,loctm_hour_of_day,loctm_minute_of_hour,loctm_second_of_min
502741,6413,1,117264,934.49,5,62,N,4,N,N,0,5,N,0,3,275,53099,N,5817,102,0,1549254,20,0,0
994932,6189,1,117264,939.19,5,62,Y,2,N,N,0,5,N,0,4,317,90151,N,1463,102,0,1837177,22,14,28
606676,6189,1,117264,1267.47,5,62,Y,2,N,N,0,5,N,0,25,317,90151,N,1463,102,0,1859385,21,26,35
1388156,6231,1,117264,1017.37,5,62,N,5,N,N,0,5,N,0,30,277,12726,N,5817,102,0,994333,20,9,47
10441,6189,1,117264,613.81,5,62,N,4,N,N,0,5,N,0,34,263,92571,N,5817,102,0,1639576,15,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353575,5975,163884,211804,1119.11,5,62,N,5,N,N,0,5,N,0,65,288,88870,N,5817,102,0,1801193,15,52,56
1215077,6767,163884,211804,1334.91,5,62,N,5,N,N,0,5,N,0,65,247,6475,N,5817,102,0,872380,17,22,3
1225070,6767,163884,211804,1125.71,5,62,N,5,N,N,0,5,N,0,65,247,6475,N,5817,102,0,872476,17,55,48
884262,6767,163884,211804,1103.64,5,62,N,5,N,N,0,5,N,0,65,247,6475,N,5817,102,0,1658468,18,8,3
234321,6769,163884,211804,1194.66,5,62,Y,8,N,N,0,5,Y,1,74,247,82174,N,5817,102,0,437384,10,16,12

In [30]:
df = pd.concat([df_train, df_test], axis = 0)

/ldap_home/yunrui.li/.pyenv/versions/3.6.5/envs/fraud/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [32]:
df.mchno.nunique()

102783

In [4]:
df_train.groupby("bacno").apply(lambda x: len(x)).max()

1117

In [5]:
from tqdm import tqdm

In [53]:

txkey = []
y_train = []
x_train = []
x_train_2 = []
max_seq_lent = 100
feat = ["conam","locdt","loctm_hour_of_day","loctm_minute_of_hour","loctm_second_of_min"]
num_feat = len(feat)
for _, x in tqdm(df_train.head(50000).groupby(gby)):
    txkey.append("_".join([str(i) for i in x.txkey.tolist()]))
    x1 = x[feat].values
    x2 = x["mchno"].values
    #print (x2.shape)
    if x1.shape[0] > 100:
        # truncating
        x1 = x1[:100,:]
    else:
        num_pad = 100-len(x1)
        pad = np.zeros((num_pad,num_feat))
        # padding
        x1 = np.concatenate([x1,pad])

    if x2.shape[0] > 100:
        # truncating
        x2 = x2[:100]
    else:
        num_pad = 100-len(x2)
        pad = np.zeros((num_pad,))
        # padding
        x2 = np.concatenate([x2,pad])
        
    # label
    if 1 in x.fraud_ind.tolist():
        y_train.append(1)
    else:
        y_train.append(0)
    # x
    x_train.append(x1)
    x_train_2.append(x2)
    
# x_test = []
# txkey_test = []
# for _, x in tqdm(df_test.groupby(gby)):
#     txkey_test.append("_".join([str(i) for i in x.txkey.tolist()]))
#     x1 = x[feat].values
#     if x1.shape[0] > 100:
#         # truncating
#         x1 = x1[:100,:]
#     else:
#         num_pad = 100-len(x1)
#         pad = np.zeros((num_pad,num_feat))
#         # padding
#         x1 = np.concatenate([x1,pad])
#     # x
#     x_test.append(x1)

 26%|██▌       | 150/582 [00:00<00:00, 729.98it/s]

(11,)
(158,)
(9,)
(18,)
(26,)
(3,)
(36,)
(4,)
(2,)
(9,)
(8,)
(13,)
(4,)
(11,)
(5,)
(4,)
(16,)
(7,)
(3,)
(2,)
(3,)
(8,)
(16,)
(7,)
(22,)
(34,)
(5,)
(65,)
(29,)
(13,)
(1,)
(15,)
(6,)
(8,)
(6,)
(10,)
(1,)
(13,)
(10,)
(2,)
(26,)
(11,)
(66,)
(26,)
(96,)
(36,)
(6,)
(25,)
(1,)
(22,)
(14,)
(5,)
(18,)
(30,)
(96,)
(2,)
(2,)
(1,)
(4,)
(8,)
(1,)
(3,)
(10,)
(24,)
(3,)
(7,)
(2,)
(4,)
(2,)
(3,)
(5,)
(58,)
(1,)
(36,)
(24,)
(26,)
(24,)
(22,)
(8,)
(21,)
(20,)
(12,)
(4,)
(59,)
(91,)
(6,)
(1,)
(5,)
(21,)
(12,)
(3,)
(29,)
(36,)
(1,)
(1,)
(45,)
(79,)
(17,)
(5,)
(5,)
(1,)
(10,)
(46,)
(40,)
(15,)
(11,)
(5,)
(16,)
(9,)
(44,)
(25,)
(8,)
(26,)
(28,)
(3,)
(16,)
(17,)
(15,)
(39,)
(11,)
(1,)
(11,)
(31,)
(29,)
(3,)
(7,)
(6,)
(4,)
(1,)
(29,)
(23,)
(25,)
(6,)
(28,)
(1,)
(26,)
(11,)
(19,)
(27,)
(7,)
(35,)
(32,)
(17,)
(9,)
(14,)
(29,)
(12,)
(17,)
(27,)
(10,)
(43,)
(1,)
(3,)

 51%|█████     | 297/582 [00:00<00:00, 725.05it/s]

(23,)
(21,)
(7,)
(3,)
(5,)
(1,)
(14,)
(6,)
(61,)
(4,)
(6,)
(23,)
(11,)
(16,)
(4,)
(8,)
(26,)
(17,)
(5,)
(14,)
(1,)
(9,)
(3,)
(7,)
(10,)
(404,)
(3,)
(1,)
(6,)
(5,)
(12,)
(35,)
(5,)
(36,)
(11,)
(9,)
(45,)
(11,)
(8,)
(37,)
(51,)
(10,)
(22,)
(2,)
(4,)
(2,)
(8,)
(2,)
(13,)
(6,)
(18,)
(57,)
(15,)
(19,)
(2,)
(1,)
(1,)
(13,)
(22,)
(9,)
(7,)
(33,)
(1,)
(1,)
(12,)
(12,)
(10,)
(19,)
(2,)
(13,)
(1,)
(48,)
(50,)
(16,)
(7,)
(29,)
(19,)
(29,)
(9,)
(1,)
(10,)
(32,)
(14,)
(3,)
(12,)
(14,)
(8,)
(7,)
(21,)
(1,)
(17,)
(8,)
(5,)
(20,)
(80,)
(3,)
(1,)
(1,)
(12,)
(4,)
(57,)
(4,)
(13,)
(27,)
(39,)
(4,)
(6,)
(2,)
(2,)
(15,)
(14,)
(28,)
(2,)
(9,)
(2,)
(19,)
(24,)
(51,)
(1,)
(26,)
(5,)
(36,)
(20,)
(16,)
(5,)
(11,)
(3,)
(20,)
(18,)
(14,)
(7,)
(11,)
(9,)
(10,)
(3,)
(34,)
(8,)
(1,)
(38,)
(11,)
(15,)
(9,)
(8,)
(7,)
(18,)
(13,)
(9,)
(4,)
(56,)

 76%|███████▌  | 442/582 [00:00<00:00, 722.88it/s]

(32,)
(3,)
(11,)
(5,)
(14,)
(9,)
(43,)
(8,)
(11,)
(1,)
(5,)
(1,)
(4,)
(27,)
(1,)
(10,)
(9,)
(9,)
(53,)
(10,)
(3,)
(8,)
(6,)
(12,)
(26,)
(2,)
(4,)
(9,)
(45,)
(5,)
(27,)
(87,)
(10,)
(2,)
(5,)
(35,)
(1,)
(12,)
(11,)
(13,)
(9,)
(23,)
(23,)
(11,)
(4,)
(21,)
(17,)
(2,)
(25,)
(2,)
(4,)
(17,)
(3,)
(3,)
(18,)
(41,)
(3,)
(43,)
(62,)
(11,)
(1,)
(28,)
(8,)
(9,)
(12,)
(79,)
(7,)
(8,)
(8,)
(57,)
(17,)
(25,)
(6,)
(4,)
(7,)
(35,)
(2,)
(3,)
(27,)
(54,)
(11,)
(1,)
(62,)
(11,)
(1,)
(18,)
(7,)
(65,)
(1,)
(1,)
(10,)
(33,)
(17,)
(1,)
(56,)
(17,)
(6,)
(2,)
(1,)
(4,)
(17,)
(11,)
(1,)
(13,)
(7,)
(13,)
(2,)
(3,)
(2,)
(15,)
(41,)
(1,)
(18,)
(16,)
(3,)
(22,)
(23,)
(9,)
(26,)
(1,)
(21,)
(31,)
(7,)
(1,)
(21,)
(2,)
(24,)
(3,)
(21,)
(54,)
(3,)
(49,)
(20,)
(1,)
(2,)
(5,)
(5,)
(4,)
(3,)
(6,)
(20,)
(14,)
(7,)
(42,)
(3,)
(8,)
(21,)

100%|██████████| 582/582 [00:00<00:00, 727.56it/s]

(5,)
(21,)
(9,)
(69,)
(8,)
(37,)
(3,)
(41,)
(11,)
(19,)
(20,)
(47,)
(8,)
(2,)
(3,)
(5,)
(2,)
(33,)
(25,)
(2,)
(148,)
(5,)
(32,)
(28,)
(7,)
(8,)
(11,)
(25,)
(1,)
(9,)
(1,)
(52,)
(24,)
(1,)
(7,)
(4,)
(3,)
(13,)
(1,)
(1,)
(7,)
(2,)
(53,)
(1,)
(25,)
(6,)
(12,)
(44,)
(20,)
(37,)
(1,)
(19,)
(2,)
(49,)
(13,)
(5,)
(62,)
(205,)
(54,)
(4,)
(2,)
(6,)
(79,)
(1,)
(59,)
(9,)
(6,)
(27,)
(14,)
(43,)
(1,)
(17,)
(7,)
(4,)
(13,)
(4,)
(2,)
(6,)
(7,)
(4,)
(3,)
(5,)
(26,)
(47,)
(4,)
(12,)
(6,)
(2,)
(2,)
(10,)
(3,)
(7,)
(3,)
(14,)
(1,)
(6,)
(10,)
(4,)
(38,)
(4,)
(29,)
(16,)
(2,)
(6,)
(13,)
(7,)
(11,)
(1,)
(6,)
(2,)
(35,)
(18,)
(2,)
(10,)
(9,)
(5,)
(77,)
(25,)
(7,)
(16,)
(65,)
(21,)
(16,)
(14,)
(3,)
(3,)
(1,)
(16,)
(4,)
(8,)
(15,)
(2,)
(1,)

In [54]:
len(txkey),len(txkey_test)

(582, 71099)

In [55]:
x_train = np.array(x_train)
x_train_2 = np.array(x_train_2)

y_train = np.array(y_train)
x_test = np.array(x_test)
print (y_train.shape[0]==x_train.shape[0])
x_train.shape

True

(582, 100, 5)

In [9]:
np.save("x_train.npy", x_train)
np.save("y_train.npy", x_train)

In [10]:
# x_train_ = np.load("x_train.npy")

In [56]:
pd.Series(y_train).value_counts(normalize = True)

0    0.895189
1    0.104811
dtype: float64

In [12]:
x_train.shape

(95214, 100, 5)

In [37]:
x_train_2.shape

(2, 100)

In [57]:
import keras
from keras.layers import Input, Embedding, LSTM, Dense
from keras.models import Model
import numpy as np
np.random.seed(0)  # Set a random seed for reproducibility

# Headline input: meant to receive sequences of 100 integers, between 1 and 10000.
# Note that we can name any layer by passing it a "name" argument.
main_input = Input(shape=(100,5,), dtype='float32', name='main_input')
print ("main_input",main_input)
main_input_2 = Input(shape=(100,), dtype='int32', name='main_input_2')
x = main_input
#x = keras.layers.concatenate([main_input])
print ("x",x.shape)
# This embedding layer will encode the input sequence
# into a sequence of dense 512-dimensional vectors.
#x = Embedding(output_dim=512, input_dim=10000, input_length=100)(main_input)
x2 = Embedding(output_dim=15, input_dim=102783+500, input_length=100)(main_input_2)
print ("x2",x2.shape)
x = keras.layers.concatenate([x, x2], axis = 2)
print ("x",x.shape)
# A LSTM will transform the vector sequence into a single vector,
# containing information about the entire sequence
lstm_out,state_h,state_c = LSTM(10, name = "lstm_out", return_sequences = True, return_state = True)(x)
#lstm_out_feature = LSTM(32, name = "lstm_out_feature", return_sequences = True)(x)
print (lstm_out)
#auxiliary_output = Dense(1, activation='sigmoid', name='aux_output')(lstm_out)

#auxiliary_input = Input(shape=(5,), name='aux_input')

# We stack a deep densely-connected network on top
x = Dense(10, activation='relu',name="dense_one")(state_h)
x = Dense(5, activation='relu',name="dense_two")(x)
x = Dense(3, activation='relu',name="dense_three")(x)

# And finally we add the main logistic regression layer
main_output = Dense(1, activation='sigmoid', name='main_output')(x)
model = Model(inputs=[main_input, main_input_2], outputs=[main_output])
model.compile(optimizer='rmsprop', 
              loss='binary_crossentropy',
              metrics=['accuracy'],
              loss_weights=None)

main_input Tensor("main_input_11:0", shape=(?, 100, 5), dtype=float32)
x (?, 100, 5)
x2 (?, 100, 15)
x (?, 100, 20)
Tensor("lstm_out_6/transpose_1:0", shape=(?, ?, 10), dtype=float32)

In [14]:
# from sklearn.model_selection import train_test_split
# x_train_, x_test_, y_train_, y_test_ = train_test_split(
#     x_train, y_train, test_size=0.20, random_state=1030)

In [15]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [58]:
batch_size = 64
# model.fit([x_train_], y_train_,
#           batch_size=batch_size,
#           epochs=5,
#           validation_data=(x_test_, y_test_)
#          )
model.fit({'main_input': x_train, 
           'main_input_2': x_train_2,
          },
          {'main_output': y_train, 
           #'aux_output': additional_labels
          },
          epochs=10, batch_size=32, validation_split = 0.2)

Train on 465 samples, validate on 117 samples
Epoch 1/5
465/465 [==============================] - 4s 9ms/step - loss: 0.6615 - acc: 0.8796 - val_loss: 0.6094 - val_acc: 0.9573
Epoch 2/5
465/465 [==============================] - 3s 6ms/step - loss: 0.5773 - acc: 0.8796 - val_loss: 0.4681 - val_acc: 0.9573
Epoch 3/5
465/465 [==============================] - 2s 5ms/step - loss: 0.4665 - acc: 0.8796 - val_loss: 0.3531 - val_acc: 0.9573
Epoch 4/5
465/465 [==============================] - 3s 6ms/step - loss: 0.4014 - acc: 0.8796 - val_loss: 0.2845 - val_acc: 0.9573
Epoch 5/5
465/465 [==============================] - 3s 6ms/step - loss: 0.3720 - acc: 0.8796 - val_loss: 0.2441 - val_acc: 0.9573

# train

In [17]:
new_model = Model(model.inputs, model.get_layer("dense_three").output)
hidden_out = new_model.predict({'main_input': x_train})
hidden_out.shape

(95214, 3)

In [18]:
new_model = Model(model.inputs, model.get_layer("main_output").output)
prediction = new_model.predict({'main_input': x_train})
prediction.shape

(95214, 1)

In [19]:
new_model = Model(model.inputs, model.get_layer("lstm_out").output)
lstm_out, state_h, state_c = new_model.predict({'main_input': x_train})
lstm_out.shape

(95214, 100, 10)

In [20]:
key_ = []
lstm_features = []
for key, lo in zip(txkey,lstm_out):
    key_ls = key.split("_")
    actual_len = len(key_ls)
    if actual_len <= 100:
        features = lo[:actual_len]
        for k,f in zip(key_ls,features):
            key_.append(k)
            lstm_features.append(f)
            #print (k)
            #print (f)
    else:
        c = 0
        features = lo[:actual_len]
        for k,f in zip(key_ls,features):
            c+=1
            key_.append(k)
            lstm_features.append(f)
            if c==100:
                break
        for k in key_ls[100:]:
            key_.append(k)
            lstm_features.append(f)

In [21]:
no_components = 10
lstm_features = pd.DataFrame(
    lstm_features,
    columns = ["{}_latent_features_{}".format("lstm",i) for i in range(no_components)]
                            )
lstm_features

,lstm_latent_features_0,lstm_latent_features_1,lstm_latent_features_2,lstm_latent_features_3,lstm_latent_features_4,lstm_latent_features_5,lstm_latent_features_6,lstm_latent_features_7,lstm_latent_features_8,lstm_latent_features_9
0,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
2,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
3,0.0,0.761594,0.466677,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
4,0.0,0.761594,0.852588,-0.680773,0.0,-0.0,-0.761594,0.0,0.728763,0.0
...,...,...,...,...,...,...,...,...,...,...
1521782,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521783,0.0,0.761594,0.588404,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521784,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521785,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521786,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0

In [22]:
output = pd.concat(
    [pd.DataFrame(key_,columns = ["txkey"]),
     lstm_features
    ],
    axis = 1
)
output

,txkey,lstm_latent_features_0,lstm_latent_features_1,lstm_latent_features_2,lstm_latent_features_3,lstm_latent_features_4,lstm_latent_features_5,lstm_latent_features_6,lstm_latent_features_7,lstm_latent_features_8,lstm_latent_features_9
0,1549254,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1,1837177,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
2,1859385,0.0,0.761594,0.000000,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
3,994333,0.0,0.761594,0.466677,-0.680773,0.0,-0.0,-0.761594,0.0,0.000000,0.0
4,1639576,0.0,0.761594,0.852588,-0.680773,0.0,-0.0,-0.761594,0.0,0.728763,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1521782,1801193,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521783,872380,0.0,0.761594,0.588404,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521784,872476,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521785,1658468,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0
1521786,437384,0.0,0.761594,1.000000,-0.900121,0.0,-0.0,-0.761594,0.0,0.000000,0.0

# test

In [23]:
new_model = Model(model.inputs, model.get_layer("lstm_out").output)
lstm_out, state_h, state_c = new_model.predict({'main_input': x_test})
print (lstm_out.shape)

key_ = []
lstm_features = []
a = 0
for key, lo in zip(txkey_test,lstm_out):
    key_ls = key.split("_")
    actual_len = len(key_ls)
    a+=actual_len
    if actual_len <= 100:
        features = lo[:actual_len]
        for k,f in zip(key_ls,features):
            key_.append(k)
            lstm_features.append(f)
            #print (k)
            #print (f)
    else:
        c = 0
        features = lo[:actual_len]
        for k,f in zip(key_ls,features):
            key_.append(k)
            lstm_features.append(f)
            c+=1
            if c==100:
                break
        for k in key_ls[100:]:
            key_.append(k)
            lstm_features.append(f)

no_components = 10
lstm_features = pd.DataFrame(
    lstm_features,
    columns = ["{}_latent_features_{}".format("lstm",i) for i in range(no_components)]
                            )
print (lstm_features.shape)

output_test = pd.concat(
    [pd.DataFrame(key_,columns = ["txkey"]),
     lstm_features
    ],
    axis = 1
)
output_test.shape

(71099, 100, 10)
(421665, 10)

(421665, 11)

In [24]:
output_test.lstm_latent_features_0.value_counts()

 0.761594    198860
 0.000000    138136
-0.761594      9098
 0.761594       822
-0.761594       564
              ...
 0.761580         1
 0.752094         1
-0.752094         1
 0.752086         1
 0.706084         1
Name: lstm_latent_features_0, Length: 69018, dtype: int64

In [25]:
df_train.txkey.nunique()

1521787

In [26]:
df_test.txkey.nunique()

421665

In [27]:
df = pd.concat([
    output,
    output_test
], axis= 0)
df.shape

(1943452, 11)

In [29]:
df.to_csv("../fraud_detection/features/lstm_features.csv", index = False)